[package]
name = "vec-deref"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "be_le"
path = "src/be_le.rs"

[[bin]]
name = "hashmap_builder"
path = "src/hashmap_builder.rs"

[[bin]]
name = "box_vec"
path = "src/box_vec.rs"

[dependencies]
sha3 = "0.10.8"
